name = "m-draw-worker"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[[durable_objects.bindings]]
name = "TLDRAW_DURABLE_OBJECT"
class_name = "TldrawDurableObject"

[[durable_objects.bindings]]
name = "STATS_DURABLE_OBJECT"
class_name = "StatsDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "TldrawDurableObject", "StatsDurableObject" ]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "m-draw-assets"
preview_bucket_name = "m-draw-assets-preview"

[observability]
enabled = true
